export const FETCH_USER_LIST_DATA_SUCCESS = "FETCH_USER_LIST_DATA_SUCCESS";
export const FETCH_USER_LIST_DATA_ERROR = "FETCH_USER_LIST_DATA_ERROR";
export const FETCH_USER_LIST_DATA = "FETCH_USER_LIST_DATA";

export const MODIFY_USER_DATA = "MODIFY_USER_DATA";
export const MODIFY_USER_DATA_SUCCESS = "MODIFY_USER_DATA_SUCCESS";
export const MODIFY_USER_DATA_ERROR = "MODIFY_USER_DATA_ERROR";
